### ISSUE TITLE
True/Mean Anomaly Targeting

### ISSUE THREAD

**Issue by mferrie** [Noiredd/PEGAS#16]
Is it possible to pull off true or mean anomaly targeting? If so, how?

**Comment by Noiredd** [comment]
In the current version of PEGAS - it is not possible. The underlying guidance algorithm, [UPFG](https://ntrs.nasa.gov/search.jsp?R=19740004402), in the *standard ascent mode* (which PEGAS implements) leaves this element free. It is possible that other modes would allow something like that - *ascent to coast reference trajectory* looks particularly promising. But even if this is possible to implement, it's not something that would happen anytime soon.

Is there any mission where you need to do this *at ascent*? Shuttle could do stuff like launch, intercept a satellite and land within a single orbit - but other than doing something that spectacular, is there any real need to be able to target anomaly? Maybe we could work around it within the limits of PEGAS?

**Comment by mferrie** [comment]
I was thinking something like launching a GPS or iridium satellite directly into its intended orbital "slot", e.g. Ω = 45, ω = 90, ν = 15.

**Comment by Noiredd** [comment]
Generally, UPFG is good at plane angles and velocity vector - when it comes to phase-related stuff (AoP, anomaly), it just does not feel like the right tool for the job.  
Realistically speaking though, are GPS satellites launched directly into their anomaly-constrained orbits, or rather launched to some intermediate parking orbits from which they get to their final ones on their own?
