### ISSUE TITLE
Optional inclination

### ISSUE THREAD

**Issue by Patrykz94** [Noiredd/PEGAS#18]
Similarily to #6, it's a small quality of life feature so that entering the inclination is not necessary. Instead, if inclination is not defined, set it to the launch site latitude.

There are many situations, particularly if you play RP-0 career, where the orbit inclination doesn't matter. Usually those "First Artificial Satellite" or "Have X number of Kerbals in orbit for X amount of time" don't specify anything other than orbit periapsis.

**Comment by Noiredd** [comment]
Possible since a0f9f6f.
