### ISSUE TITLE
Argument of Periapsis Targeting

### ISSUE THREAD

**Issue by Patrykz94** [Noiredd/PEGAS#19]
Do you plan to add this in the future?

It would be useful in cases where you'd like to launch directly to a transfer orbit, mostly because engines in RO usually have limited ignitions while some of them have only 1, so launching to a parking orbit and then re-igniting for transfer orbit can sometimes be a problem.

**Comment by Noiredd** [comment]
Anything that can be described as "different guidance constraint" is a tough task, on the edge of practical possibility\*. PEGAS uses a guidance algorithm ([UPFG](https://github.com/Noiredd/PEGAS-MATLAB/blob/master/docs/upfg.md)) that was developed for certain objectives and assumptions. Math was laid out for those objectives, and then optimized and made into a program. At the heart, PEGAS is just a port of this program - from block diagrams to MATLAB to kOS - and a bridge between the KSP infrastructure and guidance. Stuff more related to KSP side is easier to change, while things deeply touching the guidance itself - near impossible. Math at the core is way beyond what I can work with, so major changes to UPFG itself are not possible.  
I could think about it and try to fiddle around in MATLAB, as *maybe* it is a matter of one clever hack to the [corrector](https://github.com/Noiredd/PEGAS-MATLAB/blob/master/docs/upfg.md#predictor--corrector), but it might very well turn out to be practically impossible\*.

\* - by "practically possible" I mean "possible to be done by *me* in the amount of free time that *I* usually have".
