### ISSUE TITLE
Timewarp/Kerbal Alarm Clock support

### ISSUE THREAD

**Issue by Patrykz94** [Noiredd/PEGAS#21]
Would be a nice addition if PEGAS could either kill time warp when launch time is approching, or add an alarm via KAC mod and let KAC handle it. [Documentation page for KAC here](https://ksp-kos.github.io/KOS/addons/KAC.html).

I wouldn't really recommend starting a timewarp but killing it would be useful. Easy to overshoot when doing it manually.

**Comment by Noiredd** [comment]
This is possible and potentially useful. Would require some deeper thought however - since KSP's time warping has some inertia (i.e. it takes some time to speed up time and slow back down), it can't be a simple event set at a fixed time before the launch.

I wonder what does this warp inertia depend on - is this a simulation-based thing that works for every user differently, or does it have a constant effect (e.g. warping back from 1000x to 1x overshoots by some exact value every time)...

**Comment by Patrykz94** [comment]
It could be handled the same way as Kerbal Alarm Clock does, by gradually slowing down time warp as you get closer to the launch time.

So lets say, if it's < T-15s, kill time warp completely, < T-60s slow down to x10, < T-600s slow down to x100 etc.
Here's a documentation page for it: https://ksp-kos.github.io/KOS/structures/misc/timewarp.html

**Comment by pap1723** [comment]
This would be a great feature!

**Comment by Patrykz94** [comment]
I'd be happy to add this feature and send a PR if that's fine with you @Noiredd ?

I got back into RO/RP-1 career where PEGAS is extremely useful so I'd like to add some things I think would improve it, if you don't mind?

For this feature, my plan is to use Kerbal Alarm Clock integration (I think almost everyone has KAC installed).

The settings file would contain two new variables, one setting whether the user wants alarms to be created and second one to control how long before launch it should go off (I guess 30 seconds by default).

Time warping will not start automatically, the user will need to initiate it. KAC will then kill the time warp and show a pop-up message at the specified time.

Can you let me know what you think and whether you have any suggestions?

**Comment by Noiredd** [comment]
I'll review your PR soon. One thing that I'd like to know: if I put a vehicle on the launch site, run PEGAS, have it set a KAC alarm, and then switch to another vehicle (e.g. to schedule a launch from another site, or make a correction maneuver on my interplanetary probe) and then switch back to the original vehicle, will the kOS computation state be preserved, or would I have to restart PEGAS?

**Comment by Patrykz94** [comment]
KOS CPUs are only running when they are withing the full physics range (2.5km) from the active vessel. If you go to Space Center/Tracking Station or switch to another vessel further than 2.5km away, the CPU will shutdown. Once you go back to that vessel, the CPU will start up again and you'll need to run PEGAS again.

I didn't really consider that you'd switch to a different vessel while waiting for liftoff so in that PR, as of right now, when you go back to your vessel and run PEGAS again, it will re-do it's calculations (the liftoff time should really be same as before) and create a new alarm. That means you could end up with multiple alarms for the same launch.

It should be quite easy to fix it though, I could probably add something unique like the CPU part ID to the Alarm NOTES suffix and the before creating an alarm, look through existing alarms to see if one with that ID already exists and delete it if it does.

I'll try to do that once I get home.

**Comment by Noiredd** [comment]
Ok, thanks. So, knowing that kOS breaks when you switch vehicles, nobody is going to do this anyway, so the case of multiple alarms for the same launch shouldn't even realistically appear - I'd say don't bother fixing a problem that isn't really there :) Well, unless that's two extra lines of code and you've got nothing better to do anyway haha

**Comment by Patrykz94** [comment]
I guess it's just a matter of how "userproof" you'd like it to be. Probably not worth the hassle really.

Mind you, I'll do a little more testing on this today as I think I noticed a bug with KAC (or KSP itself). After reverting to launch, it seems that KAC is not able to kill the time warp in time and overshoots.

Not really something I can fix but might be worth mentioning in the documentation if it is a repeatable thing.

**Comment by Noiredd** [comment]
Done as an [addon](https://github.com/Noiredd/PEGAS-addons). Thanks @Patrykz94!
