### ISSUE TITLE
Use PEGAS in orbital maneuvers

### ISSUE THREAD

**Issue by AleXmShef** [Noiredd/PEGAS#34]
Hello.
Is it possible to use this algorithm for executing on-orbit non-impulsive burns (i.e. to change orbital parameters of the relatively low-thrust spacecraft which is already in orbit)?
And if the answer is yes - any suggestions on how to implement this using existing code?

**Comment by Noiredd** [comment]
The short answer is no.  
The long answer is: I have been thinking about this and I've even made a few experiments in Matlab (see [my other repository](https://github.com/Noiredd/PEGAS-MATLAB)) to see if it's possible, but I just couldn't get it to work. Even for relatively simple maneuvers of magnitude around 100 m/s delta-v, UPFG just wouldn't converge (or converged to some ludicrous, impossible trajectory). I'd have to look deeper into the maths to figure out *why* it doesn't work - as of now I'm not sure whether I've been doing something wrong (e.g. with timing of such a maneuver), or maybe there's some fundamental limitation that prohibits this.  
Sadly, I'm very low on time these days and don't have enough time to properly maintain this repository (as you can see - sorry for such a late reply, btw), let alone work on major additions like that.

I've been always thinking about a separate, UPFG-based script for executing arbitrary maneuvers, e.g. for fully automated interplanetary missions - I even have a name for it already, just can't get the thing to work :rofl: If I ever succeed, however, this will almost certainly be an entirely separate tool.
