### ISSUE TITLE
Certain configurations of the flight plan cause a crash

### ISSUE THREAD

**Issue by Noiredd** [Noiredd/PEGAS#45]
PEGAS crashes if the resulting flight plan is shorter than 5 items. Problem is [on line 480 in pegas_misc.ks](https://github.com/Noiredd/PEGAS/blob/8fa0ed6436579c6c47941e15acbdd58a1323946f/kOS/pegas_misc.ks#L480).

Another crash occurs if all `sequence` events occur prior to UPFG activation. Relevant [line 406 in pegas_misc.ks](https://github.com/Noiredd/PEGAS/blob/8fa0ed6436579c6c47941e15acbdd58a1323946f/kOS/pegas_misc.ks#L406).

Fixes seem simple and I'll implement them soon, just posting here to notify that I'm aware of the bugs.

**Comment by theLXMB** [comment]
I'm happy to report your fix works even on my WIP "break what you can" rocket 😃

**Comment by theHexagoner** [comment]
Mine is still blowing up on line 406.  I'm user Kurld on the KSP forums.  Thanks.

The last time in my sequence is at 10 and the guidance kicks in at 75.

**Comment by theHexagoner** [comment]
adding another item to sequence after 75 lets it run.

**Comment by theHexagoner** [comment]
LOL after fixing that it still blows up at line 480.

AM I SURE I HAVE THE LATEST CODE?

**Comment by theHexagoner** [comment]
OK, derp. I have the latest release and this was fixed after that.  Sorry it's been a long day...
