### ISSUE TITLE
Roll control

### ISSUE THREAD

**Issue by Noiredd** [Noiredd/PEGAS#5]
To simulate real Space Shuttle launches, or any vehicles with asymmetric TVC, roll control is a necessary feature.

Simplest solution would be to add a `controls` entry containing a desired roll and time of executing the roll maneuver. A more powerful solution would be via `sequence`, allowing rolling at any time - but would that be ever useful?

**Comment by TheGrover** [comment]
This could come in handy, I personally think the more elegant solution could be necessary if the first stage or two have simple symmetric TV and an upper stage doesn't.

However, does the script actually account for thrust vectors being offset like the SSMEs or shuttle OMS? I can't see any controls available in the references to specify that, and I assume that the program assumes that all thrust acts in the direction of the navball. This can be allowed for by "controlling from here" on the engines, so KSP will tell the script which direction the engine is facing, but this wouldn't work for an arrangement like the shuttles where the engines don't all thrust the same way (the shuttles topmost engine was angles further down to account for being higher on the body of the orbiter)

However, the simple implementation is still handy for spaceplane with symmetric TV that want their wings lever to avoid their lift fouling the ascent course

**Comment by Noiredd** [comment]
@TheGrover Vehicles with offset thrust are handled on the kOS level. When PEGAS sends an attitude command, kOS automatically locates CoM and attempts to align thrust so that the vehicle is stable. It is using every means it has access to: TVC, RCS, reaction wheels, wings - so the spaceplane scenario is also covered (in the sense that aero control surfaces will automatically tilt so that the course isn't _fouled_).

Please explain though, how would you use the feature in the case when 1st stage has symmetric TVC and the upper stage doesn't?

**Comment by TheGrover** [comment]
I meant use it as you described, setting the roll program to engage later in the flight, rather than straight off the pad. Bonus points for having two distinct roll programs for different phases of flight (shuttle orbiter rolled "heads down" before jettisoning the fuel tank)

**Comment by Patrykz94** [comment]
There would definitely be situations where this is useful.
One thing, could you make it possible for user to decide how fast the roll should be executed? This is mostly a cosmetic thing, it just doesn't look good to me if the rocket does a 180 degree roll within a second or two. Alternatively, maybe just make the roll speed a reasonable value?

**Comment by Noiredd** [comment]
@Patrykz94 Roll (or pitch or yaw for that matter) speed is not directly controllable as far as I know. I fiddled around with that as even in my demo video the Atlas pitches over ridiculously fast which looks weird. The solution is to use [`SteeringManager`](http://ksp-kos.github.io/KOS_DOC/structures/misc/steeringmanager.html). Initially I fiddled around with `PIDLoop` entries (`PITCHPID`, `YAWPID`, `ROLLPID`) but manually tuning the constants is too much hassle. An easier solution is to change `MAXSTOPPINGTIME` - the lower the setting, the slower the vehicle turns.  
You are warned however, that decreasing that value had some weird negative consequences on UPFG: it often failed to converge or even find entirely wrong solutions. I didn't investigate this too deeply so I don't know the exact failure mode, but I found it to be a culprit to many problems.

For this reason I decided to not implement any turning speed controls, leaving them at default max - it causes more problems (many) than it solves (none). However, an user is free to begin their `vehicle` script with a call to `SteeringManager` and set the rates to their liking.

**Comment by gsarducci** [comment]
Is it possible to introduce a spin on a stage? I'm thinking something like Thor-Able launching something like Transit. Prior to the solid fuel 3rd stage the 2nd would spin up to stabilize the payload.

Of course, if I recall Transit had a coast period, which I think is something else you were considering for the next iteration of this. :)

**Comment by Patrykz94** [comment]
@Noiredd are you working on this at the moment, I needed roll control for my script so I made a very simple one that uses `sequence`, you can see the changes [here](https://github.com/Noiredd/PEGAS/compare/master...Patrykz94:dev-roll-control).
If you want, I could improve on that, test it on a space shuttle launch and send a PR?

**Comment by Noiredd** [comment]
@Patrykz94 I was in the process of polishing the feature when you commented. Commit ca1d982 introduces roll control in a general way: both via `controls` setting (roll occurs together with the initial pitchover maneuver) and `sequence` event. In order to preserve compatibility with your ad-hoc solution, the event type is called `roll` and roll angle key is `angle` - your vehicles should work fine.

@gsarducci I can't really see how would that be possible. AFAIK, spin-stabilization only makes sense when you want to aim at one constant vector and never deviate from it, while the whole point of PEGAS is continuously changing the steering vector.  
Feel free to open up a new issue if you can explain how would it be useful, and we can discuss this.
