### ISSUE TITLE
Southerly launches

### ISSUE THREAD

**Issue by Noiredd** [Noiredd/PEGAS#7]
Current release only supports launches in the northern direction, implicitly assuming this direction. Interestingly, `mission` has an undocumented key `launchAzimuth` allowing the user to make somewhat of a dogleg ascent by constraining the initial azimuth (which would otherwise be calculated) or a southerly launch. Unfortunately, `orbitInterceptTime` assumes the launch always happens in the northern direction and if someone actually tried forcing the southern direction, the whole algorithm would think it's going the opposite way than it should and try to _correct_ that.

This one seems easy to implement:
* `mission` should have a `direction` key of type `String`, allowing the user to choose the direction,
* `orbitInterceptTime` should respect that setting.

Rest of the algorithm should handle without need for further changes.

**Comment by TheGrover** [comment]
Could direction have three possible entries? North, South or Any? With "Any" calculating and commencing the next possible window?

**Comment by Noiredd** [comment]
I like this idea and will implement it.

**Comment by Noiredd** [comment]
Implemented in 811c12d. As planned, `mission` has a new optional key: `direction`. User can choose either `north` or `south` launch opportunity, or type in `nearest` to have PEGAS pick the nearest one.
